val = input("digite algo:")
print("Tipo: {}" .format(type(val)))
print("numérico: {}" .format(val.isnumeric()))
print("alfabeto: {}" .format(val.isalpha()))
print("alfanumérico: {}" .format(val.isalnum()))
